### PR TITLE
name_id_policy_format is a string

### PR DESCRIPTION
**Pull request by amercader**
As stated in the docs:

https://pysaml2.readthedocs.io/en/latest/howto/config.html#name-id-policy-format

But here it was assigned the `name_id_format` variable, which is a list, causing an exception.

I'm not sure if it's worth having a separate config option for `name_id_policy_format` rather than reusing `name_id_format` but if so let me know.

### CODE REVIEW

**Comment by amercader** [comment]
For reference, here's Azure AD complaining about this:

Screenshot_2021-01-12 Sign in to your account

**Comment by mbocevski** [comment]
I'm trying to think why we even included the `name_id_policy_format` in the first place, cause I'm pretty sure most commonly configured SAML backends (AD being a very common exception usually) would work without having that part of the SAML request. Best would be that this would be an optional configuration setting which by default won't be set.

**Comment by amercader** [comment]
@mbocevski sounds good, done in the last commit

**Review by mbocevski — APPROVED** [review]
LGTM

**Comment by duskobogdanovski** [comment]
Back-ported to ckan-2.8.

**Pull request merged**
