### PR TITLE
ISaml2Auth interface

### LINKED ISSUE #13: Extensibility
This extension is great and a big improvement from previous versions of ckanext-saml2. One thing I would like to know more about is your plans regarding extensibility for it.

By extensibility I mean supporting custom business logic around the SAML2 authentication for specific projects. Here are some examples (all real from projects I've worked on):

* Custom SAML config. [pysaml](https://pysaml2.readthedocs.io/en/latest/howto/config.html) has lots of configuration options and sometimes you need to tweak some of them, and it would be nice to not have to add CKAN config options to cover all cases
* Adding custom fields (plugin extras) to created/updated users based on SAML2 claims
* Adding users to organizations with different roles based on SAML2 claims
* Prevent users from editing their details in CKAN

One of the problems with the old extension is that it included code to deal with several features like these that were sepcific to one or a small number of projects, and many times involving layers of code not directly related with authentication (actions, authorization, etc). This all made the code base unnecessarily complex. I think the approach of keeping this plugin lean and focus on the core functionality is the right one.

At the same time, it's good that other plugins can extend the functionality to support custom logic. Traditionally this has been done in CKAN using interfaces that plugins can implement. Here's a quick stub of how this interface could look like:

```python
class ISaml2Auth(Interface):

    def sp_config(self, sp_config):
        """"
        Gets the config object generated by get_config() allowing plugins to tweak it
        """
        pass

    def before_user_update(self, user_dict, saml_claims):
        """
        Gets the user data dict before updating a user alongside all the claims
        contained in the SAML2 token (currently in auth_response.ava)
        """
        pass

    def before_user_create(self, user_dict, saml_claims):
        """
        Gets the user data dict before creating a user alongside all the claims
        contained in the SAML2 token
        """
        pass

    def after_login(self, resp, saml_claims):
        """
        Called once the user has been logged in, just before returning the request, and passing
        the request object, so plugins can issue redirects if needed. At this point they can use
        g.user to get the logged in user
        """
        pass
```

As I said I didn't put much thought into the actual methods and params passed but hopefully they give an idea of what I'm suggesting. Of course I'm also open to other approaches if you think there are better ones.

Let me know your thoughts. I'd be happy to contribute support for the interface if this sounds like a good way forward.

### PR DESCRIPTION
**Pull request by amercader**
Fixes #13 

This implements the first version of the `ISaml2Auth` interface as discussed in #13, allowing other plugins to hook into the Saml authentication process.

I refactored the `process_user()` method in the blueprint to make it easier to extend, so it's probably best to start with babfa44. The existing default logic remains unchanged for authenticated users:

1. If an existing CKAN user exists with the same `saml_id`, only update it if the email or fullname changed
2. If an existing CKAN user exists with the same email, update the password
3. If a CKAN user does not exist, create a new one

In addition to the above, plugins implementing `ISaml2Auth` can override the logic in points 1 and 2 to suit their needs (eg always updating the user on login).

Happy to answer any questions if there are any. Includes tests and docs

### CODE REVIEW

**Review by mbocevski — APPROVED** [review]
LGTM

**Review by duskobogdanovski — APPROVED** [review]
LGTM

**Comment by amercader** [comment]
Thanks for the quick review!

Are you planning on doing a release that include this changes at some point? Many thanks

**Comment by duskobogdanovski** [comment]
You are welcome, yes @mbocevski will release new version shortly.

**Comment by mbocevski** [comment]
@amercader Released on [pypi as 1.1.0](https://pypi.org/project/ckanext-saml2auth/1.1.0/)

**Pull request merged**
