### PR TITLE
Add CKAN 2.8

### PR DESCRIPTION
**Pull request by avdata99**
Continue from #4 

This PR:
 - Add a custom branch for CKAN 2.8 and Python2
 - Updates tests and Travis configuration

### CODE REVIEW

**Comment by mbocevski** [comment]
Looking up the user by email for 2.8 doesn't capture the scenario if user email is changed on the SAML issuer side. Would be good to note this in the Readme.

**Comment by avdata99** [comment]
> Looking up the user by email for 2.8 doesn't capture the scenario if user email is changed on the SAML issuer side. Would be good to note this in the Readme.

You are right @mbocevski. I added [this](https://github.com/keitaroinc/ckanext-saml2auth/pull/5/commits/1dae14187db20d98f40cd0a77f29eb736848e100). let me know if you think this text capture what we need to explain.

**Comment by mbocevski** [comment]
Thanks @avdata99. I want to test this out and see what happens in different scenarios such as user exists in ckan locally and vice versa. Have you tried the different scenarios?

**Comment by mbocevski** [comment]
Thinking out loud... would it make sense given python2 EOL and everything that we push this on a separate ckan-2.8 branch and keep main branch to be only 2.9? It will be easier to add functionality and features considering that upstream pysaml2 has dropped python2 support.

If we do that we can highlight in the readme of the main branch that those who want to run on ckan 2.8 and python 2 can go to the ckan-2.8 branch?

WDYT @avdata99?

**Comment by avdata99** [comment]
> Thanks @avdata99. I want to test this out and see what happens in different scenarios such as user exists in ckan locally and vice versa. Have you tried the different scenarios?

@mbocevski I test manually that we avoid user duplication this works fine. But this should be covered in new test cases.
We need to mock an external entity and cover all scenarios.

**Comment by mbocevski** [comment]
There are no good ways to mock an external saml entity, we can probably have a dummy mock that would send saml responses maybe?

**Comment by mbocevski** [comment]
> We need to mock an external entity and cover all scenarios.

There are no good ways to mock an external saml entity, we can probably have a dummy mock that would send saml responses maybe?

**Comment by avdata99** [comment]
@mbocevski Separated branches are not a bad idea. Let me propose this with my team. I am sure we can reach a valuable agreement for all

**Comment by avdata99** [comment]
> > We need to mock an external entity and cover all scenarios.
> 
> There are no good ways to mock an external saml entity, we can probably have a dummy mock that would send saml responses maybe?

I have some ideas about it. I think I can propose a simple mock for this.

**Comment by mbocevski** [comment]
> Separated branches are not a bad idea.

Great! Please circle-back with your team. We can always mark functionality we want to backport to the 2.8 branch so that we can make sure that new things being added that make sense for 2.8 are also backported.

**Comment by mbocevski** [comment]
> I think I can propose a simple mock for this.

Awesome! Would be great to have "real" SAML responses, you can capture SAML responses from a SAML entity by using a browser plugin like `SAML-tracer` and we can clean them up and use them in the mocks?

**Comment by mbocevski** [comment]
@avdata99 if the branching idea sounds good with your team, please change this PR to be merged to the `ckan-2.8` branch I just created from `main`.

**Comment by avdata99** [comment]
> @avdata99 if the branching idea sounds good with your team, please change this PR to be merged to the `ckan-2.8` branch I just created from `main`.

Thanks @mbocevski

**Comment by adborden** [comment]
@mbocevski if we leave 2.8 on a branch, will Keitaro support it until CKAN 2.8 is end-of-life? That is fine with me. Data.gov is planning on moving to CKAN 2.9 quickly anyway, but we need 2.8 as a stepping stone.

**Comment by mbocevski** [comment]
@adborden yes we will support it, moving it to its own branch is something we started doing with other extensions we support cause it makes it easier and cleaner in terms of maintenance.

**Comment by avdata99** [comment]
@mbocevski this PR was updated to point to the new branch and to handle CKAN 2.8 only

**Comment by mbocevski** [comment]
@avdata99 thanks! LGTM

**Pull request merged**
