### PR TITLE
Support RelayState (redirecting to the user-requested page)

### PR DESCRIPTION
**Pull request by amercader**
This change adds support for redirecting the user to the original page a user requested when they were redirected to the login page (ie same as the `came_from` argument on the native login). This is useful when the user is redirected to the login page after trying to access a restricted one, specially on sites that require logged in users to access any page at all.

In Saml2 this is implemented using the `RelayState` parameter, which is sent by the client to the IdP when requesting the authentication, and returned by the IdP to the ACS alongside the SamlResponse.

### CODE REVIEW

**Comment by amercader** [comment]
Let me check these tests

**Review by mbocevski — APPROVED** [review]
LGTM, just need to get the tests sorted.

**Comment by amercader** [comment]
All green now

**Review by duskobogdanovski — APPROVED** [review]
LGTM

**Pull request merged**
